"""Writes assets/speech/symbols-en.json and emoji-en.json from the Unicode CLDR English annotations.

Usage:
    python tools/cldr/generate_symbols.py <annotations.json> <derived annotations.json> <assets/speech>

The annotation files are cldr-json's cldr-annotations-full/annotations/en/annotations.json and
cldr-annotations-derived-full/annotationsDerived/en/annotations.json. Names come from CLDR's
"tts" names, except where CLDR's name is awkward to listen to (OVERRIDES).

symbols-en.json has the punctuation symbols, each with the punctuation level from which it is
spoken and whether it is kept for the synthesizer's pause when it isn't. emoji-en.json has every
other CLDR symbol: emoji (always spoken) and other symbols such as arrows and maths (from Some).
"""
import json
import os
import sys
import unicodedata

# symbol: (level, preserve)
LEVELS = {
    "!": ("All", True), ".": ("All", True), ",": ("All", True), "?": ("All", True),
    "'": ("All", False), "‘": ("All", False), "’": ("All", False),
    "“": ("All", False), "”": ("All", False),
    "\"": ("Most", False), "(": ("Most", False), ")": ("Most", False),
    "[": ("Most", False), "]": ("Most", False), "{": ("Most", False), "}": ("Most", False),
    "-": ("Most", True), ":": ("Most", True), ";": ("Most", True), "`": ("Most", False),
    "–": ("Most", True), "—": ("Most", True), "…": ("Most", True),
    "#": ("Some", False), "$": ("Some", False), "%": ("Some", False), "&": ("Some", False),
    "*": ("Some", False), "+": ("Some", False), "/": ("Some", False), "<": ("Some", False),
    "=": ("Some", False), ">": ("Some", False), "@": ("Some", False), "\\": ("Some", False),
    "^": ("Some", False), "_": ("Some", False), "|": ("Some", False), "~": ("Some", False),
    "•": ("Some", False), "§": ("Some", False), "¶": ("Some", False),
    "×": ("Some", False), "÷": ("Some", False), "±": ("Some", False),
    "°": ("Some", False), "€": ("Some", False), "£": ("Some", False),
    "¥": ("Some", False), "©": ("Some", False), "®": ("Some", False),
    "™": ("Some", False),
}

# Shorter or clearer than CLDR's names, as screen reader users know them
OVERRIDES = {
    "!": "bang", ".": "dot", "&": "and", "'": "tick", "\"": "quote", "(": "left paren", ")": "right paren",
    "[": "left bracket", "]": "right bracket", "{": "left brace", "}": "right brace",
    "-": "dash", "`": "grave", "#": "number", "*": "star", "+": "plus", "<": "less",
    "=": "equals", ">": "greater", "@": "at", "^": "caret", "_": "line", "|": "bar",
    "‘": "left tick", "’": "right tick", "“": "left quote", "”": "right quote",
    "…": "dot dot dot",
}


VARIATION_SELECTOR = "\ufe0f"


def is_emoji(symbol):
    """Emoji presentation: a sequence (ZWJ, skin tone, flag, keycap) or a pictograph."""
    if len(symbol) > 1:
        return True
    cp = ord(symbol)
    return cp >= 0x1F000 or 0x2300 <= cp <= 0x23FF or 0x2600 <= cp <= 0x27BF or 0x2B00 <= cp <= 0x2BFF


def write(path, comment, symbols, indent=1):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump({"comment": comment, "symbols": symbols}, f, ensure_ascii=False, indent=indent)
        f.write("\n")


def main(annotations_path, derived_path, output_directory):
    with open(annotations_path, encoding="utf-8") as f:
        annotations = json.load(f)["annotations"]["annotations"]
    with open(derived_path, encoding="utf-8") as f:
        derived = json.load(f)["annotationsDerived"]["annotations"]
    write_symbols(annotations, os.path.join(output_directory, "symbols-en.json"))
    write_emoji({**annotations, **derived}, os.path.join(output_directory, "emoji-en.json"))


def write_emoji(annotations, output_path):
    emoji = []
    seen = set()
    for symbol, entry in sorted(annotations.items()):
        # The variation selector is invisible and Vox ignores it when matching
        key = symbol.replace(VARIATION_SELECTOR, "")
        if not key or key in LEVELS or key in seen or not entry.get("tts"):
            continue
        # Letters and digits (superscripts, ℹ, µ) read fine as they are
        if len(key) == 1 and (key.isascii() or unicodedata.category(key)[0] in "LN"):
            continue
        seen.add(key)
        emoji.append({"symbol": key, "name": entry["tts"][0], "level": "None" if is_emoji(key) else "Some"})
    write(output_path,
          "Generated by tools/cldr/generate_symbols.py from the Unicode CLDR English annotations and derived "
          "annotations. Emoji are spoken at every punctuation level; other symbols from Some. Symbols in "
          "symbols-en.json take precedence.",
          emoji)


def write_symbols(annotations, output_path):
    symbols = []
    for symbol, (level, preserve) in LEVELS.items():
        name = OVERRIDES.get(symbol) or (annotations.get(symbol, {}).get("tts") or [None])[0]
        if not name:
            raise SystemExit(f"No name for {symbol!r}")
        symbols.append({"symbol": symbol, "name": name, "level": level, "preserve": preserve})
    write(output_path,
          "Generated by tools/cldr/generate_symbols.py from the Unicode CLDR English annotations "
          "(names), with screen reader names where CLDR's are awkward. level: the punctuation "
          "level from which the symbol is spoken (None, Some, Most, All). preserve: when not "
          "spoken, the symbol is kept so the synthesizer still pauses.",
          symbols, indent=2)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
