"""Writes assets/speech/symbols-en.json from the Unicode CLDR English annotations.

Usage:
    python tools/cldr/generate_symbols.py <cldr annotations.json> <output symbols-en.json>

The annotations file is cldr-json's
cldr-annotations-full/annotations/en/annotations.json. Names come from CLDR's "tts" names,
except where CLDR's name is awkward to listen to (OVERRIDES). Each symbol has the punctuation
level from which it is spoken and whether it is kept for the synthesizer's pause when it isn't.
"""
import json
import sys

# symbol: (level, preserve)
LEVELS = {
    "!": ("All", True), ".": ("All", True), ",": ("All", True), "?": ("All", True),
    "'": ("All", False), "‘": ("All", False), "’": ("All", False),
    "“": ("All", False), "”": ("All", False),
    "\"": ("Most", False), "(": ("Most", False), ")": ("Most", False),
    "[": ("Most", False), "]": ("Most", False), "{": ("Most", False), "}": ("Most", False),
    "-": ("Most", True), ":": ("Most", True), ";": ("Most", True), "`": ("Most", False),
    "–": ("Most", True), "—": ("Most", True), "…": ("Most", True),
    "#": ("Some", False), "$": ("Some", False), "%": ("Some", False), "&": ("Some", False),
    "*": ("Some", False), "+": ("Some", False), "/": ("Some", False), "<": ("Some", False),
    "=": ("Some", False), ">": ("Some", False), "@": ("Some", False), "\\": ("Some", False),
    "^": ("Some", False), "_": ("Some", False), "|": ("Some", False), "~": ("Some", False),
    "•": ("Some", False), "§": ("Some", False), "¶": ("Some", False),
    "×": ("Some", False), "÷": ("Some", False), "±": ("Some", False),
    "°": ("Some", False), "€": ("Some", False), "£": ("Some", False),
    "¥": ("Some", False), "©": ("Some", False), "®": ("Some", False),
    "™": ("Some", False),
}

# Shorter or clearer than CLDR's names, as screen reader users know them
OVERRIDES = {
    "!": "bang", ".": "dot", "&": "and", "'": "tick", "\"": "quote", "(": "left paren", ")": "right paren",
    "[": "left bracket", "]": "right bracket", "{": "left brace", "}": "right brace",
    "-": "dash", "`": "grave", "#": "number", "*": "star", "+": "plus", "<": "less",
    "=": "equals", ">": "greater", "@": "at", "^": "caret", "_": "line", "|": "bar",
    "‘": "left tick", "’": "right tick", "“": "left quote", "”": "right quote",
    "…": "dot dot dot",
}


def main(annotations_path, output_path):
    with open(annotations_path, encoding="utf-8") as f:
        annotations = json.load(f)["annotations"]["annotations"]
    symbols = []
    for symbol, (level, preserve) in LEVELS.items():
        name = OVERRIDES.get(symbol) or (annotations.get(symbol, {}).get("tts") or [None])[0]
        if not name:
            raise SystemExit(f"No name for {symbol!r}")
        symbols.append({"symbol": symbol, "name": name, "level": level, "preserve": preserve})
    document = {
        "comment": "Generated by tools/cldr/generate_symbols.py from the Unicode CLDR English annotations "
                   "(names), with screen reader names where CLDR's are awkward. level: the punctuation "
                   "level from which the symbol is spoken (None, Some, Most, All). preserve: when not "
                   "spoken, the symbol is kept so the synthesizer still pauses.",
        "symbols": symbols,
    }
    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(document, f, ensure_ascii=False, indent=2)
        f.write("\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
